name: 'Deploy Recipe'
description: '''
Deploy a Pangeo Forge feedstock repository to the specified Apache Beam Runner.
'''
inputs:
  select_recipe_by_label:
    description: '''
    If passed as `True`, use PR labels to selectively run recipe ids from feedstock.
    PR labels must use format ``run:{recipe_id}`` where ``recipe_id`` is a valid recipe_id
    provided in meta.yaml.
    '''
    required: false
  pangeo_forge_runner_config:
    description: 'JSON configuration for Pangeo Forge Runner CLI.'
    required: true
runs:
  using: 'docker'
  image: 'ghcr.io/pangeo-forge/deploy-recipe-action:test'
