name: 'Deploy Recipe'
description: '''
Deploy a Pangeo Forge feedstock repository to the specified Apache Beam Runner.
'''
inputs:
  pangeo_forge_runner_config:
    description: 'JSON configuration for Pangeo Forge Runner CLI.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pangeo_forge_runner_config }}
