name: Test action (file config)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: (recipes@${{ matrix.recipes-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        recipes-version: ["0.10.3"]  # , "main"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup.yaml
        with:
          recipes-version: ${{ matrix.recipes-version }}
      - name: Write local-config.json
        run: |
          cat << EOF > ./local-config.json
          {
          "BaseCommand": {
            "feedstock_subdir": "pangeo-forge-recipes/examples/feedstock"
          },
          "Bake": {
            "prune": true,
            "bakery_class": "pangeo_forge_runner.bakery.local.LocalDirectBakery"
          },
          "TargetStorage": {
            "fsspec_class": "fsspec.implementations.local.LocalFileSystem",
            "root_path": "./target"
          },
          "InputCacheStorage": {
            "fsspec_class": "fsspec.implementations.local.LocalFileSystem",
            "root_path": "./cache"
          }
          }
          EOF
      - name: "Deploy recipes"
        uses: ./
        with:
          # select_recipe_by_label: true
          pangeo_forge_runner_config: ./local-config.json
