name: Test action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: (recipes@${{ matrix.recipes-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        recipes-version: ["0.10.3"]  # , "main"]
    steps:
      - uses: actions/checkout@v4
      - name: "Clone test feedstock"
        run: |
          git clone --depth 1 --branch ${{ matrix.recipes-version }} https://github.com/pangeo-forge/pangeo-forge-recipes.git
      - name: "Deploy recipes"
        uses: ./
        with:
          # select_recipe_by_label: true
          pangeo_forge_runner_config: >
            {
            "BaseCommand": {
              "feedstock_subdir": "pangeo-forge-recipes/examples/feedstock"
            },
            "Bake": {
              "bakery_class": "pangeo_forge_runner.bakery.local.LocalDirectBakery"
            },
            "TargetStorage": {
              "fsspec_class": "fsspec.implementations.local.LocalFileSystem",
              "root_path": "./target"
            },
            "InputCacheStorage": {
              "fsspec_class": "fsspec.implementations.local.LocalFileSystem",
              "root_path": "./cache"
            }
            }
